FROM node:14

RUN mkdir -p /usr/share/jenkins

RUN curl -sSL http://mirrors.jenkins.io/war-stable/latest/jenkins.war -o /usr/share/jenkins/jenkins.war --create-dirs

RUN npm install -g npm@latest

RUN mkdir -p /home/jenkins/agent
WORKDIR /home/jenkins/agent
